apiVersion: v1
kind: BuildConfig
metadata:
  name: ci-cd-demo
  labels:
    app: php-sample-app
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "php-sample-app", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
  - type: GitHub
    github:
      secret: a04aabf8d0002f77
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
         node {
           stage('buildImage'){
             openshiftBuild(buildConfig: 'php-sample-app', showBuildLogs: 'true')
           }
           stage('deployApplication'){
             openshiftDeploy(deploymentConfig: 'php-sample-app')
           }
         }
